image: Ubuntu2204

environment:
  DOCKER_REGISTRY_USERNAME:
    secure: dmyPzjP6KShV/FiJ215A4Q==
  DOCKER_REGISTRY_PASSWORD:
    secure: UYs7PFiQeHyLhEFJeiMpH3Osuu83IlFZBZCpgF2zAmNNiANRYh5JWkq0rG2gxyhE

pull_requests:
  do_not_increment_build_number: true

init:
  - sh: echo $DOCKER_REGISTRY_PASSWORD | docker login --username="$DOCKER_REGISTRY_USERNAME" --password-stdin docker.zvirja.com

# This is a a workaround before .NET 8 is not installed to Ubuntu image
before_build:
  - sh: wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sh: sudo dpkg -i packages-microsoft-prod.deb
  - sh: sudo apt update && sudo apt install -y dotnet-sdk-8.0

build_script:
  - sh: chmod +x ./build.sh
  - sh: ./build.sh --target AppVeyor_Pipeline --build-version git  --build-number $APPVEYOR_BUILD_NUMBER --no-logo

test: off

artifacts: off

deploy: off
